### ISSUE TITLE
Release Backlog - A holder for high priority issues not yet assigned to a release

### ISSUE THREAD

**Issue by jsirois** [pex-tool/pex#686]
+ [x] Multi-interpreter feature doesn't work perfectly #415
+ [x] Support PEP-518 builders #660
+ [x] Not all changes to setup.py invalidate the cache. #620
+ [x] resolver bugs:
  + [x] Dependency resolution can't handle PEP 503-style normalized package names #641
  + [x] Pex resolution does not properly constrain sdists. #628 
  + [x] pex 1.5.1 bombs at runtime with missing deps error when extras are transitively pulled in for existing packages with concrete requirement specs in the resolve scope #616
  + [x] Pex cannot correctly resolve between multiple transitive dependencies #614
  + [x] Resolve seems to be inconsistent in python 3.4 #611
  + [x] pex fails to resolve wheels when a sdist is present in the cache #608
